# Comment to a new issue.
issueOpened: >
  Thank your for raising a issue. We will try and get back to you as soon as possible.

  Please make sure you have given us as much context as possible.
  
  <img align="center" width="150" height="150" src="https://github.com/msandfor/10-Easy-Steps/blob/master/assets/leomeme.gif?raw=true"></a>

pullRequestOpened: >
  Thank your for raising your pull request.

  Please make sure you have followed our contributing guidelines. We will review it as soon as possible
  
  <img align="center" width="150" height="150" src="https://github.com/msandfor/10-Easy-Steps/blob/master/assets/Snickersmeme.gif?raw=true"></a>
  
